In [1]:
import pandas as pd

df = pd.read_csv('../data/cosine_similairity_neigbor.csv', index_col=0)
df.head()

,avg_neighbor_cosine,avg_cosine,language,model,embedding_model,country
0,0.180427,0.216585,english,GPT-5.3 Chat,fastText (aligned),US
1,0.170836,0.195003,english,GPT-5.3 Chat,fastText (aligned),US
2,0.161853,0.198587,english,GPT-5.3 Chat,fastText (aligned),US
3,0.215940,0.217909,french,GPT-5.3 Chat,fastText (aligned),US
4,0.196636,0.220473,french,GPT-5.3 Chat,fastText (aligned),US

In [2]:
df.model.unique()

array(['GPT-5.3 Chat', 'Grok 4.1', 'Sonnet 4.6', 'DeepSeek-V3.2',
       'Gemini 3', 'Qwen3.5-Plus', 'Human', 'mistral-medium',
       'mistral-large-2402', 'mistral-small-2402', 'Trinity-Mini',
       'GLM-4.5-Air'], dtype=object)

In [3]:
# Add country

country_mapping = {
    'GPT-5.3 Chat': 'US',
    'Grok 4.1': 'US',
    'Sonnet 4.6': 'US',
    'DeepSeek-V3.2': 'China',
    'Gemini 3': 'US',
    'Qwen3.5-Plus':'China',
    'Human': 'N/A',
    'mistral-medium': 'France',
    'mistral-large-2402': 'France',
    'mistral-small-2402': 'France',
    'Trinity-Mini': 'US',
    'GLM-4.5-Air': 'China',

}

In [4]:
# add country to df
df['country'] = df['model'].map(country_mapping)
df

,avg_neighbor_cosine,avg_cosine,language,model,embedding_model,country
0,0.180427,0.216585,english,GPT-5.3 Chat,fastText (aligned),US
1,0.170836,0.195003,english,GPT-5.3 Chat,fastText (aligned),US
2,0.161853,0.198587,english,GPT-5.3 Chat,fastText (aligned),US
3,0.215940,0.217909,french,GPT-5.3 Chat,fastText (aligned),US
4,0.196636,0.220473,french,GPT-5.3 Chat,fastText (aligned),US
...,...,...,...,...,...,...
139,0.521037,0.503652,french,Human,paraphrase-multilingual-MiniLM-L12-v2,N/A
140,0.397077,0.410418,french,Human,paraphrase-multilingual-MiniLM-L12-v2,N/A
141,0.437405,0.412692,french,Human,paraphrase-multilingual-MiniLM-L12-v2,N/A
142,0.488346,0.493166,french,Human,paraphrase-multilingual-MiniLM-L12-v2,N/A
143,0.470110,0.475713,french,Human,paraphrase-multilingual-MiniLM-L12-v2,N/A

In [5]:
size_mapping = {
    'GPT-5.3 Chat': 'XL',
    'Grok 4.1': 'XL',
    'Sonnet 4.6': 'XL',
    'DeepSeek-V3.2': 'XL',
    'Gemini 3': 'XL',
    'Qwen3.5-Plus':'XL',
    'Human': 'N/A',
    'mistral-medium': 'M',
    'mistral-large-2402': 'L',
    'mistral-small-2402': 'S',
    'Trinity-Mini': 'S',
    'GLM-4.5-Air': 'L',

}

# add size to df
df['size'] = df['model'].map(size_mapping)
df

,avg_neighbor_cosine,avg_cosine,language,model,embedding_model,country,size
0,0.180427,0.216585,english,GPT-5.3 Chat,fastText (aligned),US,XL
1,0.170836,0.195003,english,GPT-5.3 Chat,fastText (aligned),US,XL
2,0.161853,0.198587,english,GPT-5.3 Chat,fastText (aligned),US,XL
3,0.215940,0.217909,french,GPT-5.3 Chat,fastText (aligned),US,XL
4,0.196636,0.220473,french,GPT-5.3 Chat,fastText (aligned),US,XL
...,...,...,...,...,...,...,...
139,0.521037,0.503652,french,Human,paraphrase-multilingual-MiniLM-L12-v2,N/A,N/A
140,0.397077,0.410418,french,Human,paraphrase-multilingual-MiniLM-L12-v2,N/A,N/A
141,0.437405,0.412692,french,Human,paraphrase-multilingual-MiniLM-L12-v2,N/A,N/A
142,0.488346,0.493166,french,Human,paraphrase-multilingual-MiniLM-L12-v2,N/A,N/A
143,0.470110,0.475713,french,Human,paraphrase-multilingual-MiniLM-L12-v2,N/A,N/A

In [6]:
df.to_csv('../data/cosine_similairity_neigbor.csv')