In [1]:
import pandas as pd

df = pd.read_csv('../data/cosine_similairity.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,language,model,embedding_model,avg_cosine,country
0,0,0,english,GPT-5.3 Chat,fastText (aligned),0.216585,US
1,1,1,english,GPT-5.3 Chat,fastText (aligned),0.195003,US
2,2,2,english,GPT-5.3 Chat,fastText (aligned),0.198587,US
3,3,3,french,GPT-5.3 Chat,fastText (aligned),0.217909,US
4,4,4,french,GPT-5.3 Chat,fastText (aligned),0.220473,US

In [2]:
df.model.unique()

array(['GPT-5.3 Chat', 'Gork 4.1', 'Sonnet 4.6', 'DeepSeek-V3.2',
       'Gemini 3', 'Gwen3.5-Plus', 'Human', 'mistral-medium-2508',
       'mistral-large-2402', 'mistral-small-2402', 'Trinity-Mini',
       'GLM-4.5-Air'], dtype=object)

In [3]:
# Add country

country_mapping = {
    'GPT-5.3 Chat': 'US',
    'Gork 4.1': 'US',
    'Sonnet 4.6': 'US',
    'DeepSeek-V3.2': 'China',
    'Gemini 3': 'US',
    'Gwen3.5-Plus':'China',
    'Human': 'N/A',
    'mistral-medium-2508': 'France',
    'mistral-large-2402': 'France',
    'mistral-small-2402': 'France',
    'Trinity-Mini': 'US',
    'GLM-4.5-Air': 'China',

}

In [4]:
# add country to df
df['country'] = df['model'].map(country_mapping)
df

,Unnamed: 0.1,Unnamed: 0,language,model,embedding_model,avg_cosine,country
0,0,0,english,GPT-5.3 Chat,fastText (aligned),0.216585,US
1,1,1,english,GPT-5.3 Chat,fastText (aligned),0.195003,US
2,2,2,english,GPT-5.3 Chat,fastText (aligned),0.198587,US
3,3,3,french,GPT-5.3 Chat,fastText (aligned),0.217909,US
4,4,4,french,GPT-5.3 Chat,fastText (aligned),0.220473,US
...,...,...,...,...,...,...,...
571,571,139,french,Human,paraphrase-multilingual-MiniLM-L12-v2,0.503652,N/A
572,572,140,french,Human,paraphrase-multilingual-MiniLM-L12-v2,0.410418,N/A
573,573,141,french,Human,paraphrase-multilingual-MiniLM-L12-v2,0.412692,N/A
574,574,142,french,Human,paraphrase-multilingual-MiniLM-L12-v2,0.493166,N/A
575,575,143,french,Human,paraphrase-multilingual-MiniLM-L12-v2,0.475713,N/A

In [5]:
df.to_csv('../data/cosine_similairity.csv')